-- backend/docs/supabase-schema.sql

-- 1. User Profiles
create table if not exists user_profiles (
  id          bigint generated by default as identity primary key,
  firebase_uid text unique not null,
  name        text,
  email       text,
  resume_data jsonb default '{}'::jsonb,
  skills      jsonb default '[]'::jsonb,
  created_at  timestamptz default now(),
  updated_at  timestamptz default now()
);

-- 2. Resume AI History
create table if not exists resume_ai_history (
  id          bigint generated by default as identity primary key,
  firebase_uid text not null,
  resume      jsonb,
  score       int,
  gaps        jsonb,
  suggestions jsonb,
  created_at  timestamptz default now()
);

-- 3. Community Posts
create table if not exists community_posts (
  id          bigint generated by default as identity primary key,
  firebase_uid text not null,
  content     text,
  created_at  timestamptz default now()
);

-- 4. Community Comments
create table if not exists community_comments (
  id          bigint generated by default as identity primary key,
  post_id     bigint references community_posts(id) on delete cascade,
  firebase_uid text not null,
  comment     text,
  created_at  timestamptz default now()
);

-- 5. Community Likes
create table if not exists community_likes (
  id          bigint generated by default as identity primary key,
  post_id     bigint references community_posts(id) on delete cascade,
  firebase_uid text not null,
  created_at  timestamptz default now(),
  unique(firebase_uid, post_id)
);

-- 6. Job History
create table if not exists job_history (
  id          bigint generated by default as identity primary key,
  firebase_uid text not null,
  job_title   text,
  created_at  timestamptz default now()
);

-- RPC Function for incrementing likes (optional but good to have)
create or replace function increment_post_likes(x bigint)
returns void as $$
begin
  -- This is a placeholder; usually you'd just count rows in community_likes
  -- or update a counter column in community_posts if you have one.
  -- For now, we assume the code calls this but maybe it's not strictly needed if we count rows.
end;
$$ language plpgsql;
